config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'questions#index'
  put 'questions/:id/track_view', to: 'questions#track_view', as: 'track_view'
  resources :questions do
    resources :answers, except: [:show] do
      resources :comments, except: [:show], module: :answers
      resources :votes, only:[:create,:update, :destroy], module: :answers
    end
    resources :votes, only:[:create,:update, :destroy], module: :questions
    resources :comments, except: [:show], module: :questions
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  title      :string
#  content    :text
#  active     :datetime
#  viewed     :integer
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :votes, as: :votable, dependent: :destroy
  belongs_to :user
  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/questions/comments_controller.rb
class Questions::CommentsController < CommentsController
  before_action :set_commentable

  private
    def set_commentable
      @commentable = Question.find(params[:question_id])
    end
end

app/controllers/questions/votes_controller.rb
class Questions::VotesController < VotesController
  before_action :set_votable

  private
    def set_votable
      @votable = Question.find(params[:question_id])
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :update, :detroy]
  before_action :set_question, except: [:index, :new, :create]
  before_action :set_ransack

  def index
    if params[:q].present?
      @questions = @search.result
    else
      @questions = Question.all
    end
  end

  def show
  end

  def new
    @question = Question.new
  end

  def edit
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    if @question.save
      redirect_to question_path(id: @question.id)
    else
      flash[:alert] = "The Question hasn't been created, due an error"
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to question_path
    else
      flash[:alert] = "The Question hasn't been edited, due an error"
    end
  end


  def destroy
    @question.destroy
    redirect_to questions_path
  end

  def track_view
    @question.update(viewed: @question.viewed + 1)
    redirect_to question_path(@question)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end
    def set_ransack
      @search = Question.search(params[:q])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :content)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answer_panel.html.erb
<div class="answer" id="answer-<%= answer.id %>">
  <div class="row">
    <div class="col-sm-1">
      <% if user_signed_in? %>
        <% vote = Vote.already_vote?(current_user, answer) %>
        <% if vote %>
          <%= render 'votes/votes_panel', { votable: answer, path_up: question_answer_vote_path(answer.question, answer, vote),
            path_down: question_answer_vote_path(answer.question, answer, vote), verb: :delete } %>
        <% else %>
        <%= render 'votes/votes_panel', { votable: answer, path_up: question_answer_votes_path(question, answer, liked: true),
          path_down: question_answer_votes_path(question, answer, liked: false), verb: :post } %>
        <% end %>
      <% end %>
    </div>
    <div class="col-sm-9">
      <div class="content-body">
        <%= markdown(answer.content) %>
      </div>
    </div>
    <div class="col-sm-2">
      <%= render 'questions/info_panel', { data: answer, question: answer.question,
        path_edit: edit_question_answer_path(answer.question, answer), path_delete: question_answer_path(answer.question, answer) } %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-9 col-sm-offset-1">
      <% if user_signed_in? %>
        <%= render 'comments/add_comment', { path: [question, answer, Comment.new], commentable: answer } %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-9 col-sm-offset-1">
      <div class="comment-list">
        <%= render 'questions/comment_list', commentable: answer %>
      </div>
    </div>
  </div>
</div>

app/views/questions/_comment_list.html.erb
<table class="table">
  <tbody class="visible-comments-<%= commentable.class.name %>-<%= commentable.id %>">
    <% commentable.comments.order('created_at DESC').limit(3).each do |comment| %>
        <%= render comment, commentable: commentable %>
    <% end %>
  </tbody>
  <% if commentable.comments.count > 3 %>
    <tr class="more-comments" id="more-comments-<%= commentable.id %>">
      <td>
        <a href="javascript:void(0)" data-toggle="collapse" data-target="#more-comments-<%= commentable.id %>" id="show-more-<%= commentable.id %>">Show <%= commentable.comments.count - 3 %> more</a>
      </td>
    </tr>
    <tbody class="collapse" id="more-comments-<%= commentable.id %>">
      <% commentable.comments.order('created_at DESC').drop(3).each do |comment| %>
        <%= render comment, commentable: commentable %>
      <% end %>
    </tbody>
  <% end %>
</table>

<% if commentable.comments.count > 3 %>
  <script type="text/javascript">
  $("#show-more-<%= commentable.id %>").on('click', function() {
    $("#more-comments-<%= commentable.id %>").remove()
  });
  </script>
<% end %>

app/views/questions/_form.html.erb
<%= form_for(question) do |f| %>
  <% if question.errors.any? %>
    <div id="errors_explanation">
      <h2><%= pluralize(question.errors.count,"error") %> Prohibited this product from being saved:</h2>
      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: "form-control", rows: 10 %>
  </div>
  <div>
    <%= f.submit 'Ask', class:"btn btn-primary btn-sm" %>
    <%= link_to 'Cancel', questions_path, class: 'btn btn-default btn-sm' %>
  </div>
<% end %>

app/views/questions/_info_panel.html.erb
<table class="info-panel">
  <tbody>
    <tr>
      <td><strong>User</strong><%=" #{data.user.email.split('@')[0].humanize}" %></td>
    </tr>
    <tr>
      <td><strong><%= data.kind_of?(Question) ? "Asked" : "Answered" %></strong><%=" #{time_ago_in_words( data.created_at ).humanize} ago" %></td>
    </tr>
    <% if data.kind_of?(Question) %>
      <tr>
        <td><strong>Active</strong><%= " #{time_ago_in_words(data.active).humanize} ago" %></td>
      </tr>
      <tr>
        <td><strong>Views</strong><%= " #{data.viewed}" %></td>
      </tr>
    <% end %>
    <tr>
      <td class="actions">
        <div class="fb-share-button" data-href=<%="http://flow-overstack.herokuapp.com" + question_path(question) %> data-layout="button" data-size="small" data-mobile-iframe="true">
          <a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse">Share</a>
        </div>
        <% if user_signed_in? && current_user == data.user  %>
          <% if data.kind_of?(Question) %>
            <h3 class="icons"><%= link_to "", path_edit, class: 'fa fa-pencil-square-o' %></h3>
            <h3 class="icons"><%= link_to "", path_delete, class: 'fa fa-trash', method: :delete, data: { confirm: 'Are you sure?' }  %></h3>
          <% else %>
            <h3 class="icons"><%= link_to "", path_edit, class: 'fa fa-pencil-square-o', remote: true %></h3>
            <h3 class="icons"><%= link_to "", path_delete, class: 'fa fa-trash', method: :delete, remote: true, data: { confirm: 'Are you sure?' }  %></h3>
          <% end %>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>

app/views/questions/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center">Editing Question</h1>
      <%= render 'form', question: @question %>
    </div>
  </div>
</div>

app/views/questions/index.html.erb
<div class="container question-index">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <div class="subheader">
        <h3 class="text-center">Top Questions</h3>
        <%= link_to 'Ask Question', new_question_path, class:"btn btn-primary btn-sm" %>
      </div>
      <table class="table questions-list">
        <tbody>
          <% @questions.each do |question| %>
            <tr>
              <td class="metric">
                <span class="metric-value"><%= question.votes.count %></span>
                <span class="metric-label">Votes</span>
              </td>
              <td class="metric">
                <span class="metric-value"><%= question.answers.count %></span>
                <span class="metric-label">Answers</span>
              </td>
              <td class="metric">
                <span class="metric-value"><%= question.viewed %></span>
                <span class="metric-label">Views</span>
              </td>
              <td class="question-info">
                <span class="question-title"><%= link_to truncate(question.title.humanize, length: 150), track_view_path(id: question.id), method: :put %></span>
                <span class="question-details"><%= link_to "#{question.user.email.split('@')[0]}, #{time_ago_in_words(question.created_at)} ago" , question %></span>
              </td>
              <td>
                <% if user_signed_in? && current_user == question.user  %>
                  <div class="actions">
                    <h3 class="icons"><%= link_to "", edit_question_path(question), class: 'fa fa-pencil-square-o' %></h3>
                    <h3 class="icons"><%= link_to "", question_path(question), class: 'fa fa-trash', method: :delete, data: { confirm: 'Are you sure?' }  %></h3>
                  </div>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center">New Question</h1>
      <%= render 'form', question: @question %>
    </div>
  </div>
</div>

app/views/questions/show.html.erb
<% content_for :head do %>
  <meta property="fb:app_id"             content=212950962480498>
  <meta property="og:url"                content=<%="http://flow-overstack.herokuapp.com" + question_path(@question) %> />
  <meta property="og:type"               content="article" />
  <meta property="og:title"              content="<%= @question.title %>" />
  <meta property="og:description"        content="<%= @question.content.first(255) %>" />
  <meta property="og:image"              content="http://i558.photobucket.com/albums/ss29/Jefferson_Bernal_Cardona/programador_zpsilox3uwn.jpg" />
<% end %>
<!-- Load Facebook SDK for JavaScript -->
<div id="fb-root"></div>
<script>
$(document).ready(function (){
    // thinks to do on document load
    (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8&appId=212950962480498";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
});
</script>
<div class="container question-show">
  <div class="col-sm-12">
    <div class="row">
      <div class="col-sm-11 col-sm-offset-1">
        <div class="subheader">
          <div class="question-header"><h2><%= @question.title.humanize %></h2></div>
          <%= link_to 'Ask Question', new_question_path, class:"btn btn-primary btn-sm" %>
        </div>
      </div>
    </div>
    <div class="question-panel">
      <div class="row">
        <div class="col-sm-1">
          <% if user_signed_in? %>
            <% vote = Vote.already_vote?(current_user, @question) %>
            <% if vote %>
              <%= render 'votes/votes_panel', { votable: @question, path_up: question_vote_path(@question, vote),
                path_down: question_vote_path(@question, vote), verb: :delete } %>
            <% else %>
              <%= render 'votes/votes_panel', { votable: @question, verb: :post,
                path_up: question_votes_path(@question, liked: true),
                path_down: question_votes_path(@question, liked: false) } %>
            <% end %>
          <% end %>
        </div>
        <div class="col-sm-9">
          <div class="question-body">
            <%= markdown(@question.content) %>
          </div>
        </div>
        <div class="col-sm-2">
          <%= render 'info_panel', { data: @question, question: @question,
            path_edit: edit_question_path(@question), path_delete: question_path(@question) } %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-9 col-sm-offset-1">
        <%= render 'comments/add_comment', { path: [@question, Comment.new], commentable: @question } %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-9 col-sm-offset-1">
        <div class="comment-list">
          <%= render 'comment_list', commentable: @question %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-sm-12">
    <h4 class="text-center"><%="#{@question.answers.size} Respuesta(s)" %></h4>
      <div class="answers-list">
        <% @question.answers.each do |answer| %>
          <%= render 'answer_panel', { answer: answer, question: @question } %>
        <% end %>
      </div>
      <div class="col-sm-9 col-sm-offset-1">
        <div class="row">
          <% if user_signed_in? %>
            <%= render 'answers/form', answer: @question.answers.build %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>