config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'questions#index'
  put 'questions/:id/track_view', to: 'questions#track_view', as: 'track_view'
  resources :questions do
    resources :answers, except: [:show] do
      resources :comments, except: [:show], module: :answers
      resources :votes, only:[:create,:update, :destroy], module: :answers
    end
    resources :votes, only:[:create,:update, :destroy], module: :questions
    resources :comments, except: [:show], module: :questions
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id               :integer          not null, primary key
#  content          :text
#  commentable_type :string
#  commentable_id   :integer
#  user_id          :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  validates :content, presence: true
end

app/controllers/answers/comments_controller.rb
class Answers::CommentsController < CommentsController
  before_action :set_commentable

  private
    def set_commentable
      @commentable = Answer.find(params[:answer_id])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:edit, :destroy, :update]

  def create
    @comment = @commentable.comments.new(comment_params)
    @comment.user = current_user
    @comment.save
    render 'comments/create.js'
  end

  def edit
    if @commentable.kind_of?(Question)
      @path = [@commentable, @comment]
    else
      @path = [@commentable.question, @commentable, @comment]
    end
  end

  def update
    @comment.update(comment_params)
    render 'comments/update.js'
  end

  def destroy
    @comment.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/questions/comments_controller.rb
class Questions::CommentsController < CommentsController
  before_action :set_commentable

  private
    def set_commentable
      @commentable = Question.find(params[:question_id])
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_add_comment.html.erb
<% if user_signed_in? %>
  <div class="add-comment" >
    <a href="javascript:void(0)" id="add-comment-<%= commentable.class.name %>-<%= commentable.id %>"
      data-toggle="collapse" data-target="#comment-<%= commentable.class.name %>-<%= commentable.id %>">
      Add Comment
    </a>
  </div>
  <div class="collapse" id="comment-<%= commentable.class.name %>-<%= commentable.id %>">
    <%= render 'comments/form', { path: path, commentable: commentable } %>
  </div>
<% end %>

<script type="text/javascript">
$('#add-comment-<%= commentable.class.name %>-<%= commentable.id %>').on('click', function() {
  $('#add-comment-<%= commentable.class.name %>-<%= commentable.id %>').remove()
});
</script>

app/views/comments/_comment.html.erb
<tr>
  <td class="comment" id="<%= comment.id %>">
    <div class="comment-body"><%= markdown(comment.content).humanize %> -
      <span class="comment-user">
        <%= comment.user.email.split('@')[0].humanize %> -
        <%= comment.created_at.strftime("%b %d '%y") %>
      </span>
      <% if comment.user == current_user %>
        <span class="icons">
          <% if comment.commentable.kind_of?(Question) %>
            <%= link_to ''.html_safe, edit_question_comment_path(id: comment.id, question_id: comment.commentable.id), class: 'fa fa-pencil-square-o', remote: true -%>
            <%= link_to ''.html_safe, question_comment_path(id: comment.id, question_id: comment.commentable.id), method: :delete, data: {confirm: "Are you sure you want to delete this comment?"}, class: 'fa fa-trash', remote: true %>
          <% elsif comment.commentable.kind_of?(Answer) %>
            <%= link_to ''.html_safe, edit_question_answer_comment_path(id: comment.id, question_id: comment.commentable.question.id, answer_id: comment.commentable.id), class: 'fa fa-pencil-square-o', remote: true -%>
            <%= link_to ''.html_safe, question_answer_comment_path(id: comment.id, question_id: comment.commentable.question.id, answer_id: comment.commentable.id), method: :delete, data: {confirm: "Are you sure you want to delete this comment?"}, class: 'fa fa-trash', remote: true %>
          <% end %>
        </span>
      <% end %>
    </div>
  </td>
</tr>

app/views/comments/_form.html.erb
<%= form_for(path,  remote: true) do |f| %>
  <div class="form-group">
    <%= f.text_area :content, class:"form-control", id: "comment-content-#{commentable.class.name}-#{commentable.id}", placeholder: "Add a comment" %>
  </div>
  <div class="actions">
    <%= f.submit 'Coment', class: "btn btn-primary btn-sm" %>
    <button class="btn btn-default btn-sm" data-toggle="collapse" data-target="#comment-<%= commentable.class.name %>-<%= commentable.id %>">Close</a>
  </div>
<% end %>

app/views/comments/create.js.erb
<% if @comment.errors.empty?  %>
  $('.visible-comments-<%= @commentable.class.name %>-<%= @commentable.id %>').prepend(' <%= j render "comments/comment", comment: @comment %>');
  $('#comment-content-<%= @commentable.class.name %>-<%= @commentable.id %>').val("");
  $('#comment-<%= @commentable.class.name %>-<%= @commentable.id %>').remove();
<% end %>

app/views/comments/destroy.js.erb
$('#<%= @comment.id %>').remove();

app/views/comments/edit.js.erb
$("#<%= @comment.id %>").replaceWith("<%= j render 'comments/form', { path: @path, commentable: @commentable } %>");

app/views/comments/update.js.erb
<% if @comment.errors.empty? %>
  $('#edit_comment_<%= @comment.id %>').replaceWith(' <%= j render "comments/comment", comment: @comment %>');
<% end %>