config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'questions#index'
  put 'questions/:id/track_view', to: 'questions#track_view', as: 'track_view'
  resources :questions do
    resources :answers, except: [:show] do
      resources :comments, except: [:show], module: :answers
      resources :votes, only:[:create,:update, :destroy], module: :answers
    end
    resources :votes, only:[:create,:update, :destroy], module: :questions
    resources :comments, except: [:show], module: :questions
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/vote.rb
# == Schema Information
#
# Table name: votes
#
#  id           :integer          not null, primary key
#  liked        :boolean
#  votable_type :string
#  votable_id   :integer
#  user_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Vote < ApplicationRecord
  belongs_to :votable, polymorphic: true
  belongs_to :user

  scope :votes_up, -> { where(liked: true) }
  scope :votes_down, -> { where(liked: false) }

  def calculate_votes(votable)
    votable.votes.votes_up.count - votable.votes.votes_down.count
  end

  def self.already_vote?(user, votable)
    votable.votes.find_by(user_id: user.id)
  end
end

app/controllers/answers/votes_controller.rb
class Answers::VotesController < VotesController
  before_action :set_votable

  private
    def set_votable
      @votable = Answer.find(params[:answer_id])
    end
end

app/controllers/questions/votes_controller.rb
class Questions::VotesController < VotesController
  before_action :set_votable

  private
    def set_votable
      @votable = Question.find(params[:question_id])
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def create
    @vote = @votable.votes.new(vote_params)
    @vote.user = current_user
    @vote.save
    @votes = @vote.calculate_votes(@votable)
  end

  def destroy
    @vote = Vote.find(params[:id])
    @vote.destroy
    @votes = @vote.calculate_votes(@votable)
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def vote_params
      params.permit(:liked)
    end

end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/votes/_votes_panel.html.erb
<div class="votes-cell <%= 'already-vote' if verb == :delete  %>" id="votes-<%= votable.class.name %>-<%= votable.id %>">
  <%= link_to '<span class="glyphicon glyphicon-triangle-top vote-icon" aria-hidden="true"></span> '.html_safe, path_up, method: verb, remote: true  %>
  <span class="total-votes" id="total-votes-<%= votable.class.name %>-<%= votable.id %>"><%= votable.votes.votes_up.count - votable.votes.votes_down.count %></span>
  <%= link_to '<span class="glyphicon glyphicon-triangle-bottom vote-icon" aria-hidden="true"></span> '.html_safe, path_down, method: verb, remote: true  %>
</div>

app/views/votes/create.js.erb
$("#total-votes-<%= @votable.class.name %>-<%= @votable.id %>").text(<%= @votes %>);
<% if @votable.kind_of?(Question) %>
  $("#votes-<%= @votable.class.name %>-<%= @votable.id %>").replaceWith('<%= j render "votes_panel", { votable: @votable, path_up: question_vote_path(@votable, @vote), path_down: question_vote_path(@votable, @vote), verb: :delete } %>');
  $("#votes-<%= @votable.class.name %>-<%= @votable.id %>").addClass('already-vote')
<% else %>
  $("#votes-<%= @votable.class.name %>-<%= @votable.id %>").replaceWith('<%= j render "votes_panel", { votable: @votable, path_up: question_answer_vote_path(@votable.question, @votable, @vote), path_down: question_answer_vote_path(@votable.question, @votable, @vote), verb: :delete } %>');
  $("#votes-<%= @votable.class.name %>-<%= @votable.id %>").addClass('already-vote')
<% end %>

app/views/votes/destroy.js.erb
$("#total-votes-<%= @votable.class.name %>-<%= @votable.id %>").text(<%= @votes %>);
<% if @votable.kind_of?(Question) %>
  $("#votes-<%= @votable.class.name %>-<%= @votable.id %>").replaceWith('<%= j render "votes_panel", { votable: @votable, verb: :post, path_up: question_votes_path(@votable, liked: true), path_down: question_votes_path(@votable, liked: false) } %>');
  $("#votes-<%= @votable.class.name %>-<%= @votable.id %>").removeClass('already-vote')
<% else %>
  $("#votes-<%= @votable.class.name %>-<%= @votable.id %>").replaceWith('<%= j render "votes_panel", { votable: @votable, verb: :post, path_up: question_answer_votes_path(@votable.question, @votable, liked: true), path_down: question_answer_votes_path(@votable.question, @votable, liked: false) } %>');
  $("#votes-<%= @votable.class.name %>-<%= @votable.id %>").removeClass('already-vote')
<% end %>