config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'questions#index'
  put 'questions/:id/track_view', to: 'questions#track_view', as: 'track_view'
  resources :questions do
    resources :answers, except: [:show] do
      resources :comments, except: [:show], module: :answers
      resources :votes, only:[:create,:update, :destroy], module: :answers
    end
    resources :votes, only:[:create,:update, :destroy], module: :questions
    resources :comments, except: [:show], module: :questions
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_alerts.html.erb
<div class="alerts text-center">
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Flow<strong>Overstack</strong></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
          <%= search_form_for(@search, url: questions_path, html: { class: 'navbar-form navbar-left' }) do |f| %>
            <div class="form-group"> <%= f.search_field :title_or_content_cont, class: 'form-control', placeholder: 'Search' %></div>
            <div class="actions">
              <%= button_tag type: 'submit', class: "glyphicon glyphicon-search" do %>
              <% end %>
            </div>
          <% end %>
        <% if user_signed_in? %>
          <li><%= link_to '', new_question_path, class:'fa fa-plus' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email.split('@')[0].upcase %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'New Question',new_question_path %></li>
              <li> <%= link_to 'Log Out', destroy_user_session_path, method: :delete %> </li>
            </ul>
          </li>
        <% else %>
          <li> <%= link_to 'Log In', new_user_session_path %> </li>
          <li> <%= link_to 'Sign Up', new_user_registration_path %> </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlowOverstack</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <% if content_for?(:head) %>
      <%= yield(:head) %>
    <% end %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/alerts' %>
    <%= yield %>
    <footer id="footer">
        <p>&copy; 2017 <a href="#">Flow<strong>Overstack</strong></a>, Powered by Rails</p>
    </footer>
    <script>
      $(".alert").fadeIn(500).css("opacity","0.85").delay(6000).slideUp(1000);
      $('.alerts').on('click','.alert',function(){ $(this).remove()});
    </script>
  </body>
</html>